"""Add unique constraints to Report model

Revision ID: d7742f120cc4
Revises: f1b28c22b2a5
Create Date: 2025-06-16 13:15:43.370046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7742f120cc4'
down_revision = 'f1b28c22b2a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_report_per_product', ['reporter_id', 'product_id'])
        batch_op.create_unique_constraint('unique_report_per_user', ['reporter_id', 'reported_user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_constraint('unique_report_per_user', type_='unique')
        batch_op.drop_constraint('unique_report_per_product', type_='unique')

    # ### end Alembic commands ###
