"""Add ondelete=cascade to user foreign keys

Revision ID: edcadb61e114
Revises: 192ff348fd04
Create Date: 2025-06-16 11:37:47.583651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edcadb61e114'
down_revision = '192ff348fd04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.drop_constraint('cart_items_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['buyer_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint('orders_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['buyer_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('payouts', schema=None) as batch_op:
        batch_op.drop_constraint('payouts_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['seller_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_constraint('reports_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('reports_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['reporter_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['reported_user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint('reviews_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('search_history', schema=None) as batch_op:
        batch_op.drop_constraint('search_history_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('wishlists', schema=None) as batch_op:
        batch_op.drop_constraint('wishlists_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wishlists', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('wishlists_ibfk_1', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('search_history', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('search_history_ibfk_1', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('reviews_ibfk_1', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('reports_ibfk_2', 'users', ['reported_user_id'], ['id'])
        batch_op.create_foreign_key('reports_ibfk_1', 'users', ['reporter_id'], ['id'])

    with op.batch_alter_table('payouts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('payouts_ibfk_1', 'users', ['seller_id'], ['id'])

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('orders_ibfk_1', 'users', ['buyer_id'], ['id'])

    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('cart_items_ibfk_1', 'users', ['buyer_id'], ['id'])

    # ### end Alembic commands ###
