"""Add ondelete=cascade to user foreign keys like orderitems

Revision ID: f1b28c22b2a5
Revises: edcadb61e114
Create Date: 2025-06-16 11:41:11.054331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1b28c22b2a5'
down_revision = 'edcadb61e114'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_constraint('order_items_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'orders', ['order_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('order_items_ibfk_1', 'orders', ['order_id'], ['id'])

    # ### end Alembic commands ###
